apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ilab-train
spec:
  params:
  - name: generate-results-repo
    type: string
    description: Git repository where the data generation results are stored
    default: "https://github.com/bbrowning/konflux-taxonomy.git"
  - name: generate-results-revision
    type: string
    description: The Git ref to use when cloning the data generation results repo
    default: main
  - name: generate-results-subdir
    type: string
    description: The subdirectory within the data generation results (cloned git repository or directory downloaded from S3) directory that contains the results
    default: pre-generated
  - name: generate-results-bucket-dir
    type: string
    description: The directory in the S3 bucket containing the generated data
    default: ""
  - name: train-deepspeed
    type: string
    description: Whether to deploy with DeepSpeed training or not
    default: "true"
  - name: train-lora-rank
    type: string
    description: LoRA rank to use, 0 to disable LoRA
    default: "16"
  - name: train-num-epochs
    type: string
    description: Number of epochs during training
    default: "10"
  - name: deploy-model
    description: Whether to deploy the newly built model
    default: "false"
  results:
  - name: train-results-bucket-host
    description: The S3 bucket host containing the training results
    value: $(tasks.save-to-s3.results.bucket-host)
  - name: train-results-bucket-name
    description: The S3 bucket name containing the training results
    value: $(tasks.save-to-s3.results.bucket-name)
  - name: train-results-bucket-dir
    description: The directory in the S3 bucket containing the training results
    value: $(tasks.save-to-s3.results.dir)
  tasks:

  - name: fetch-generation-results-git
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: "$(params.generate-results-repo)"
    - name: revision
      value: "$(params.generate-results-revision)"
    when:
    - input: "$(workspaces.ilab-bucket.bound)"
      operator: in
      values: ["false"]
    workspaces:
    - name: output
      workspace: shared-data

  - name: pull-from-s3
    taskRef:
      kind: Task
      name: pull-from-s3
    params:
    - name: s3-dir
      value: "$(params.generate-results-bucket-dir)"
    - name: local-dir
      value: generated
    when:
    - input: "$(workspaces.ilab-bucket.bound)"
      operator: notin
      values: ["false"]
    workspaces:
    - name: taxonomy
      workspace: shared-data
    - name: bucket-config
      workspace: ilab-bucket

  - name: ilab-train
    taskRef:
      kind: Task
      name: ilab-train
    retries: 2
    runAfter:
      - fetch-generation-results-git
      - pull-from-s3
    params:
    - name: num-epochs
      value: "$(params.train-num-epochs)"
    timeout: 4h
    when:
    - input: "$(params.train-deepspeed)"
      operator: notin
      values: ["true"]
    workspaces:
    - name: workspace
      workspace: shared-data
    - name: huggingface-cache
      workspace: huggingface-cache

  - name: ilab-train-deepspeed
    taskRef:
      kind: Task
      name: ilab-train-deepspeed
    retries: 2
    runAfter:
      - fetch-generation-results-git
      - pull-from-s3
    params:
    - name: generate-results-subdir
      value: "$(params.generate-results-subdir)"
    - name: lora-rank
      value: "$(params.train-lora-rank)"
    - name: num-epochs
      value: "$(params.train-num-epochs)"
    timeout: 4h
    when:
    - input: "$(params.train-deepspeed)"
      operator: in
      values: ["true"]
    workspaces:
    - name: workspace
      workspace: shared-data
    - name: huggingface-cache
      workspace: huggingface-cache

  - name: save-to-s3
    taskRef:
      kind: Task
      name: save-to-s3
    runAfter:
    - ilab-train
    - ilab-train-deepspeed
    params:
    - name: artifact-type
      value: train
    - name: prune-older-than
      value: 30d
    when:
    - input: "$(workspaces.ilab-bucket.bound)"
      operator: notin
      values: ["false"]
    workspaces:
    - name: taxonomy
      workspace: shared-data
    - name: bucket-config
      workspace: ilab-bucket

  workspaces:
  - name: shared-data
  - name: huggingface-cache
  - name: ilab-bucket
    optional: true
